import { motion } from "framer-motion";
import { ArrowLeft, ScrollText, ShieldCheck } from "lucide-react";
import { Link } from "react-router";
import { Button } from "@/components/ui/button";
import logo from "@/assets/logo.png";
import { useSeo } from "@/hooks/use-seo";

type LegalKind = "terms" | "privacy";

const LAST_UPDATED = "September 23, 2026";

const TERMS: { heading: string; body: string[] }[] = [
  {
    heading: "1. Acceptance of terms",
    body: [
      "By accessing or using SeedText (the \"Service\"), you agree to these Terms of Service. If you do not agree, please do not use the Service.",
    ],
  },
  {
    heading: "2. What SeedText provides",
    body: [
      "SeedText is a free web application that generates AI-drafted Markdown article outlines and drafts from a keyword and a content style you choose. The Service is provided free of charge, subject to fair-use limits we may apply to keep it available for everyone.",
    ],
  },
  {
    heading: "3. Accounts",
    body: [
      "You can use the Service as a guest or create an account with email. You are responsible for activity that happens through your session, and for keeping your sign-in method secure.",
      "Guest sessions are temporary by design: drafts generated in guest mode are not saved and are lost when you sign out or close your session.",
    ],
  },
  {
    heading: "4. Acceptable use",
    body: [
      "You agree not to use the Service to generate unlawful, harmful, deceptive, or infringing content; not to attempt to disrupt, overload, reverse-engineer, or resell the Service; and not to automate access in a way that degrades it for others. We may suspend access that violates these rules.",
    ],
  },
  {
    heading: "5. AI-generated content",
    body: [
      "Drafts are generated by AI models and may contain inaccuracies, outdated information, or generic phrasing. You are responsible for reviewing, fact-checking, and editing anything you publish that originates from a SeedText draft.",
      "You own the drafts you generate and may edit, publish, and monetize them. We claim no ownership over your inputs or outputs.",
    ],
  },
  {
    heading: "6. Intellectual property",
    body: [
      "The SeedText name, logo, design, and website code are the property of SeedText. Nothing in these terms transfers ownership of the Service to you or grants you the right to rebrand or redistribute it.",
    ],
  },
  {
    heading: "7. Availability and changes",
    body: [
      "The Service is provided \"as is\" and \"as available.\" We may add, change, suspend, or discontinue any part of it at any time, including fair-use limits on the free tier. We aim for high availability but do not guarantee uninterrupted access.",
    ],
  },
  {
    heading: "8. Disclaimers and limitation of liability",
    body: [
      "To the maximum extent permitted by law, SeedText disclaims all warranties not stated in these terms and will not be liable for indirect, incidental, or consequential damages arising from your use of the Service, including reliance on AI-generated content.",
    ],
  },
  {
    heading: "9. Changes to these terms",
    body: [
      "We may update these terms from time to time. The \"last updated\" date above reflects the current version, and continued use of the Service after changes means you accept the updated terms.",
    ],
  },
  {
    heading: "10. Contact",
    body: [
      "Questions about these terms? Reach us at hello@seedtext.app.",
    ],
  },
];

const PRIVACY: { heading: string; body: string[] }[] = [
  {
    heading: "1. Overview",
    body: [
      "SeedText collects as little data as the product allows. This policy explains what we collect, why, and how you stay in control — especially the difference between guest mode and a signed-in account.",
    ],
  },
  {
    heading: "2. What we collect",
    body: [
      "Signed-in accounts: your email address, plus the drafts you save to your Seed Vault history.",
      "Guest sessions: nothing. Guest mode runs on a temporary anonymous session that stores no profile, email, or history, and guest drafts are never written to our database.",
    ],
  },
  {
    heading: "3. What we deliberately don't collect",
    body: [
      "No advertising cookies, no cross-site trackers, no behavioral profiles, no analytics that identify you. The workspace keyword and style you type are used only to generate your draft in that moment.",
    ],
  },
  {
    heading: "4. How your data is used",
    body: [
      "Your email is used for sign-in codes and account security. Your saved drafts are stored so you can reopen, copy, or load them later, and are visible only to you. We do not sell personal data.",
    ],
  },
  {
    heading: "5. AI generation processing",
    body: [
      "To generate a draft, your keyword and chosen style are sent to our AI provider's API, where the draft is produced. Your Seed Vault contents are not sent to AI providers. AI providers process generation requests under their own terms; avoid submitting sensitive personal information as a keyword.",
    ],
  },
  {
    heading: "6. Third-party processors",
    body: [
      "SeedText runs on Convex (application hosting and database). Sign-in codes are delivered by our email provider. These parties process data only to operate the Service.",
    ],
  },
  {
    heading: "7. Local storage",
    body: [
      "We store your authentication session token in your browser's local storage so you stay signed in. That's it — no tracking storage.",
    ],
  },
  {
    heading: "8. Retention and deletion",
    body: [
      "Vault drafts stay until you delete them (one tap in the Seed Vault). Signing out removes access from the device. To delete your account and its data entirely, email hello@seedtext.app and we'll remove it.",
    ],
  },
  {
    heading: "9. Children",
    body: [
      "The Service is not directed to children under 13, and we do not knowingly collect their data.",
    ],
  },
  {
    heading: "10. Changes and contact",
    body: [
      "We may update this policy as the Service evolves; the date above reflects the current version. Questions or deletion requests: hello@seedtext.app.",
    ],
  },
];

const CONTENT: Record<
  LegalKind,
  {
    title: string;
    description: string;
    icon: typeof ScrollText;
    sections: { heading: string; body: string[] }[];
  }
> = {
  terms: {
    title: "Terms of Service — SeedText",
    description:
      "The terms that govern your use of SeedText, the free AI article draft studio.",
    icon: ScrollText,
    sections: TERMS,
  },
  privacy: {
    title: "Privacy Policy — SeedText",
    description:
      "What SeedText collects, what it deliberately doesn't, and how guest mode and accounts differ.",
    icon: ShieldCheck,
    sections: PRIVACY,
  },
};

export default function Legal({ kind }: { kind: LegalKind }) {
  useSeo();
  const meta = CONTENT[kind];
  const Icon = meta.icon;

  return (
    <div className="glass-scene relative min-h-screen overflow-x-clip">
      {/* Ambient orbs behind the glass */}
      <div aria-hidden className="pointer-events-none absolute inset-0">
        <div className="glass-orb left-[-8rem] top-[-6rem] size-[24rem] bg-sky-300/50" />
        <div className="glass-orb right-[-6rem] bottom-[-4rem] size-[22rem] bg-indigo-300/40" />
      </div>

      {/* ── Nav ─────────────────────────────────────────────────── */}
      <header className="sticky top-0 z-40 px-4 pt-4">
        <div className="glass-panel mx-auto flex h-14 max-w-3xl items-center justify-between rounded-2xl px-4">
          <Link to="/" className="flex items-center gap-2.5">
            <img src={logo} alt="" className="size-8" />
            <span className="text-[15px] font-bold tracking-tight text-foreground">
              SeedText
            </span>
          </Link>
          <Button
            asChild
            variant="outline"
            className="rounded-xl border-white/60 bg-white/50"
          >
            <Link to="/">
              <ArrowLeft className="size-4" />
              Back to home
            </Link>
          </Button>
        </div>
      </header>

      {/* ── Document ────────────────────────────────────────────── */}
      <main className="relative mx-auto max-w-3xl px-4 pb-20 pt-10">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45 }}
          className="glass-panel rounded-3xl p-6 sm:p-10"
        >
          <div className="flex items-center gap-3">
            <div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
              <Icon className="size-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight text-foreground">
                {kind === "terms" ? "Terms of Service" : "Privacy Policy"}
              </h1>
              <p className="text-xs text-muted-foreground">
                Last updated {LAST_UPDATED}
              </p>
            </div>
          </div>

          <div className="mt-8 space-y-8">
            {meta.sections.map((section) => (
              <section key={section.heading}>
                <h2 className="text-[15px] font-semibold text-foreground">
                  {section.heading}
                </h2>
                {section.body.map((paragraph, i) => (
                  <p
                    key={i}
                    className="mt-2 text-sm leading-relaxed text-muted-foreground"
                  >
                    {paragraph}
                  </p>
                ))}
              </section>
            ))}
          </div>

          <div className="mt-10 flex flex-col gap-3 border-t border-white/50 pt-6 text-sm sm:flex-row sm:items-center sm:justify-between">
            <p className="text-muted-foreground">
              {kind === "terms" ? (
                <>
                  Also read our{" "}
                  <Link
                    to="/privacy"
                    className="font-medium text-primary hover:underline"
                  >
                    Privacy Policy
                  </Link>
                  .
                </>
              ) : (
                <>
                  Also read our{" "}
                  <Link
                    to="/terms"
                    className="font-medium text-primary hover:underline"
                  >
                    Terms of Service
                  </Link>
                  .
                </>
              )}
            </p>
            <Button asChild className="rounded-xl">
              <Link to="/dashboard">
                <ScrollText className="size-4" />
                Open the workspace
              </Link>
            </Button>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
